<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Default language is English
$lang = isset($_SESSION['lang']) ? $_SESSION['lang'] : 'en';

// Switch language if requested via URL
if (isset($_GET['lang']) && in_array($_GET['lang'], ['en', 'ar', 'id'])) {
    $_SESSION['lang'] = $_GET['lang'];
    $lang = $_GET['lang'];
    
    // Redirect to the same page without the query parameters for clean URL
    $redirect_url = strtok($_SERVER['REQUEST_URI'], '?');
    header("Location: " . $redirect_url);
    exit;
}

$translations = [
    'en' => [
        'dir' => 'ltr',
        'brand' => 'Quran Analytics',
        'home' => 'Home',
        'dashboard' => 'Dashboard',
        'quran' => 'Holy Quran',
        'miracles' => 'Scientific Miracles',
        'manage_miracles' => 'Manage Miracles',
        'manage_users' => 'Manage Users',
        'welcome' => 'Welcome',
        'guest' => 'Guest',
        'sign_in' => 'Sign In',
        'become_contributor' => 'Become a Contributor',
        'logout' => 'Logout',
        'dakwah_badge' => 'A Dakwah Platform for Quranic Insights',
        'hero_title' => 'Explore the Divine Wonders of the',
        'hero_span' => 'Holy Quran',
        'hero_desc' => 'Welcome to Quran Analytics. A modern educational resource dedicated to sharing scientific miracles of the Holy Quran in fields like astronomy, oceanography, geology, and human biology. Revealed 14 centuries ago, the divine text stands in perfect harmony with modern empirical discoveries.',
        'btn_explore' => 'Explore Scientific Miracles',
        'btn_browse_quran' => 'Browse Holy Quran',
        'stat_verses' => 'Quranic Verses In DB',
        'stat_miracles' => 'Documented Miracles',
        'stat_contributors' => 'Active Contributors',
        'card_seeker_title' => 'For Seekers & Learners',
        'card_seeker_desc' => 'This platform is kept 100% free and open, with absolutely no login required for general browsing. It is designed to be highly accessible and intuitive for friends, students, and seekers of truth.',
        'bullet_seeker_1' => 'Read Quranic verses in authentic Uthmani script.',
        'bullet_seeker_2' => 'Perform instant keyword search across all verses.',
        'bullet_seeker_3' => 'Read compiled scientific consensus maps for every topic.',
        'btn_start_browsing' => 'Start Browsing Directory',
        'card_contributor_title' => 'Join as a Contributor',
        'card_contributor_desc' => 'Are you passionate about research and scientific miracles of the Quran? Register as a contributor to add and update entries, link them to specific verses, and help enrich our database.',
        'bullet_contributor_1' => 'Submit new topics with references & scientific data.',
        'bullet_contributor_2' => 'Secure pending-to-active validation by superadmins.',
        'bullet_contributor_3' => 'Maintain research integrity under absolute security.',
        'btn_register_account' => 'Register Contributor Account',
        'footer_copyright' => 'Quran Analytics. Sharing the miracles of the Quran worldwide.',
        'footer_tag' => 'Developed for Dakwah & Educational purposes.',
        'superadmin_console' => 'Superadmin Console',
        'lang_en' => 'English',
        'lang_ar' => 'العربية',
        'lang_id' => 'Bahasa Indonesia',
        
        // login.php & register.php intro
        'login_intro_title' => 'Quranic Analytics & Scientific Miracles Project',
        'login_intro_desc' => 'Welcome to the interactive digital platform dedicated to displaying and studying the scientific miracles in the Holy Quran. Search verses, explore cosmic/medical proofs, and monitor statistics via the dashboard.',
        'feat_quran_title' => 'Browse Holy Quran & Search',
        'feat_quran_desc' => 'Smart and instant search interface to access verses, track word occurrences, and Quranic topics.',
        'feat_miracles_title' => 'Scientific Miracles Encyclopedia',
        'feat_miracles_desc' => 'Explore miracles classified scientifically (astronomy, geology, medicine, seas) in an engaging, fact-supported manner.',
        'feat_dash_title' => 'Analytics & Smart Content Management',
        'feat_dash_desc' => 'Interactive dashboard for admins and students to monitor statistics, manage users, and scientific miracles.',
        
        // login.php
        'login_title' => 'Sign In | Session Management System',
        'auth_portal' => 'Identity Verification Portal',
        'auth_subtitle' => 'Secure Session Gateways & Quranic Analytics',
        'username' => 'Username',
        'password' => 'Password',
        'enter_username' => 'Enter username',
        'enter_password' => 'Enter password',
        'no_account' => "Don't have an account?",
        'register_here' => 'Register a new account here',
        'demo_accounts' => 'Demo Accounts (Hashed/Plain):',
        'demo_admin' => 'Username: admin | Password: admin123',
        'demo_user' => 'Username: demo | Password: demo123',
        'copyright' => 'All rights reserved',
        'logout_success' => 'You have successfully logged out.',
        'pending_approval' => 'Your contributor account is pending approval by the Superadmin. Please check back later!',
        'invalid_credentials' => 'Invalid username or password.',
        'role_superadmin' => 'Superadmin',
        'role_contributor' => 'Contributor',
        
        // register.php
        'register_title' => 'Register | Quran Analytics',
        'create_account' => 'Create Account',
        'join_portal' => 'Join the Quran Analytics & Miracles Portal',
        'confirm_password' => 'Confirm Password',
        'choose_username' => 'Choose a username',
        'at_least_6' => 'At least 6 characters',
        'repeat_password' => 'Repeat your password',
        'register_button' => 'Register Account',
        'already_have' => 'Already have an account?',
        'sign_in_here' => 'Sign In Here',
        'all_fields_required' => 'Please fill in all required fields.',
        'passwords_dont_match' => 'Passwords do not match.',
        'password_too_short' => 'Password must be at least 6 characters long.',
        'username_taken' => 'Username is already taken, please choose another.',
        'reg_error' => 'An error occurred during registration, please try again later.',
        'reg_success' => 'Account created! Pending Superadmin verification before you can log in. Redirecting...',
        
        // dashboard.php
        'dash_title' => 'Dashboard | Quran Analytics',
        'dash_heading' => 'Dashboard Analytics & Quran Data',
        'dash_subheading' => 'Welcome back! Monitor database statistics and explore integrated scientific miracles in the Holy Quran.',
        'scientific_pointers' => 'Scientific Pointers',
        'topics' => 'Topics',
        'imported_verses' => 'Imported Verses',
        'verses' => 'Verses',
        'session_privilege' => 'Session Privilege',
        'superadmin_full' => 'Superadmin (Full Access)',
        'contributor_add_edit' => 'Contributor (Add/Edit)',
        'available_modules' => 'Available Modules',
        'sql_quran_browser' => 'SQL Holy Quran Browser',
        'quran_browser_desc' => 'Browse verses of the Holy Quran directly from your SQL database. Perform fast keyword searches and view translation data instantly.',
        'browse_verses' => 'Browse Verses',
        'miracles_dir_desc' => 'Explore scientific statements in the Holy Quran, linking divine words directly with modern discoveries in geology, astronomy, and oceanography.',
        'explore_dir' => 'Explore Directory',
        'manage_miracles_desc' => 'Contribute new research topics, edit summaries, or enrich the database of Quranic scientific wonders.',
        'superadmin_control_desc' => 'Review, verify, and activate pending contributors or manage admin accounts to maintain platform security.',
        'about_project' => 'About Project',
        'about_desc' => 'A modern educational web platform linking Quranic studies with scientific realities. Developed in PHP and integrated with MySQL/MariaDB using XAMPP for high performance and security.',
        'platform_highlights' => 'Platform Highlights',
        'protected_sessions' => 'Protected Session Gateways',
        'prepared_statements' => 'Prepared SQL Statements',
        'sanitized_inputs' => 'Sanitized Form Inputs',
        
        // quran.php
        'quran_title' => 'Holy Quran | Quran Analytics',
        'quran_heading' => 'Browse & Search Holy Quran (SQL Database)',
        'quran_subheading' => 'Search through verses of the Holy Quran, or fetch the entire scripture via the one-click installer.',
        'download_quran_btn' => 'Download Complete Quran via API (1-Click)',
        'select_surah' => 'Select Surah',
        'no_data_download' => 'No data (Please click the Download button above)',
        'search_keywords' => 'Search Keywords (Uthmani Arabic or English Surah name)',
        'search_placeholder' => 'Type search keyword... (e.g. الحديد, Al-Hadid)',
        'search_button' => 'Search',
        'no_verses_found' => 'No verses found',
        'no_verses_desc' => 'Make sure you have typed a valid keyword or clicked on "Download Complete Quran" above to populate the database.',
        'surah_label' => 'Surah',
        'verse_label' => 'Verse',
        'import_conn_error' => 'Unable to connect to the external Quran API. Please check your internet connection or try again later.',
        'import_success' => 'Success! Loaded all %d verses directly into your local SQL database.',
        'import_parse_error' => 'Failed to parse data received from the external API.',
        
        // miracles.php
        'miracles_title' => 'Scientific Miracles | Quran Analytics',
        'miracles_heading' => 'Scientific Miracles in the Holy Quran',
        'miracles_subheading' => 'Explore geological, cosmic, and terrestrial phenomena detailed in the Quran 14 centuries ago.',
        'search_miracles_placeholder' => 'Search scientific miracles... (e.g. Iron, Seas)',
        'quran_meaning_context' => 'Quranic Meaning & Context',
        'modern_scientific_verification' => 'Modern Scientific Verification',
        'no_miracles_found' => 'No miracles found',
        'no_miracles_desc' => 'Try searching using different keywords.',
        'download_quran_prompt' => '(Please click "Download Complete Quran" on the Holy Quran page to display the verse here)',
        
        // manage_miracles.php
        'edit_miracle' => 'Edit Scientific Miracle',
        'add_miracle' => 'Add Scientific Miracle',
        'fill_fields_link' => 'Fill out the fields below to link the entry to a specific Quranic verse.',
        'miracle_title_label' => 'Miracle Topic Title',
        'title_placeholder' => 'e.g. Iron Sent Down from space',
        'surah_number_label' => 'Surah Number',
        'ayah_number_label' => 'Verse Number (Ayah)',
        'meaning_context_desc' => 'Quranic Meaning & Context (Description)',
        'context_placeholder' => 'Describe the divine context and background...',
        'scientific_proof_label' => 'Modern Scientific Proof',
        'proof_placeholder' => 'Detail the astrophysical, geological, or oceanic discoveries...',
        'update_entry' => 'Update Entry',
        'add_to_encyclopedia' => 'Add to Encyclopedia',
        'cancel_edit' => 'Cancel Edit',
        'manage_existing_entries' => 'Manage Existing Entries',
        'browse_modify_delete' => 'Browse through the scientific miracles, modify their details, or delete them.',
        'miracle_title_th' => 'Miracle Title',
        'reference_th' => 'Reference',
        'actions_th' => 'Actions',
        'edit_action' => 'Edit',
        'delete_action' => 'Delete',
        'confirm_delete_miracle' => 'Are you sure you want to delete this scientific miracle entry permanently?',
        'no_records_found' => 'No records found in database. Create one using the form on the left.',
        'add_success' => 'Scientific miracle successfully added!',
        'add_error' => 'An error occurred while inserting data.',
        'update_success' => 'Scientific miracle successfully updated!',
        'update_error' => 'An error occurred while updating data.',
        'delete_success' => 'Scientific miracle successfully deleted.',
        'delete_error' => 'An error occurred while deleting data.',
        
        // manage_users.php
        'manage_users_title' => 'Manage Users | Quran Analytics',
        'add_new_user' => 'Add New User',
        'register_user_privileges' => 'Register a new system user with standard contributor or administrative privileges.',
        'user_role_label' => 'User Role',
        'role_contributor_option' => 'Contributor (Add & Edit Miracles)',
        'role_superadmin_option' => 'Superadmin (Full Access)',
        'register_user_btn' => 'Register User Account',
        'system_user_directory' => 'System User Directory',
        'browse_verify_users' => 'Browse through registered users, verify contributors, manage roles, and delete accounts.',
        'username_th' => 'Username',
        'access_level_th' => 'Access Level',
        'status_th' => 'Status',
        'reg_date_th' => 'Registration Date',
        'current_session' => 'Current Session',
        'approve_action' => 'Approve',
        'suspend_action' => 'Suspend',
        'confirm_delete_user' => 'Are you sure you want to delete this user permanently?',
        'no_users_found' => 'No records found in database.',
        'username_taken_error' => 'Username is already taken. Please choose another one.',
        'user_reg_success' => 'User successfully registered!',
        'user_reg_error' => 'Failed to insert user into database.',
        'self_delete_error' => 'Security Alert: You cannot delete your own logged-in admin account!',
        'user_delete_success' => 'User successfully deleted.',
        'user_delete_error' => 'An error occurred while deleting user.',
        'contributor_approved' => 'Contributor account approved and activated successfully!',
        'contributor_approve_error' => 'Failed to approve contributor.',
        'self_suspend_error' => 'Security Alert: You cannot suspend your own logged-in admin account!',
        'contributor_suspended' => 'User account successfully suspended.',
        'contributor_suspend_error' => 'Failed to suspend account.',
        'status_active' => 'Active',
        'status_pending' => 'Pending',
        'status_suspended' => 'Suspended',
    ],
    'ar' => [
        'dir' => 'rtl',
        'brand' => 'تحليلات القرآن',
        'home' => 'الرئيسية',
        'dashboard' => 'لوحة التحكم',
        'quran' => 'القرآن الكريم',
        'miracles' => 'الإعجاز العلمي',
        'manage_miracles' => 'إدارة الإعجاز',
        'manage_users' => 'إدارة المستخدمين',
        'welcome' => 'مرحباً بك',
        'guest' => 'زائر',
        'sign_in' => 'تسجيل الدخول',
        'become_contributor' => 'كن مساهماً معنا',
        'logout' => 'تسجيل الخروج',
        'dakwah_badge' => 'منصة دعوية لبيان معجزات القرآن الكريم',
        'hero_title' => 'اكتشف روائع الإعجاز العلمي في',
        'hero_span' => 'القرآن الكريم',
        'hero_desc' => 'مرحبًا بكم في منصة تحليلات القرآن. مصدر تعليمي ودعوي مخصص لمشاركة معجزات القرآن الكريم العلمية في مجالات الفلك، والبحار، والجيولوجيا، والأحياء. نزل هذا الكتاب منذ 14 قرناً ليتوافق تماماً مع الاكتشافات العلمية الحديثة.',
        'btn_explore' => 'استكشف معجزات القرآن',
        'btn_browse_quran' => 'تصفح المصحف الشريف',
        'stat_verses' => 'الآيات المخزنة بقاعدة البيانات',
        'stat_miracles' => 'مواضيع الإعجاز الموثقة',
        'stat_contributors' => 'المساهمون النشطون',
        'card_seeker_title' => 'للباحثين ومتعلمين',
        'card_seeker_desc' => 'هذه المنصة مجانية ومفتوحة بالكامل، ولا تطلب تسجيل الدخول للتصفح العام، صممت لتكون بسيطة وسهلة الاستخدام لجميع الطلاب والباحثين عن الحقيقة.',
        'bullet_seeker_1' => 'قراءة الآيات الكريمة بالرسم العثماني الأصيل.',
        'bullet_seeker_2' => 'البحث الفوري بالكلمات المفتاحية في جميع الآيات.',
        'bullet_seeker_3' => 'الاطلاع على التوافق العلمي الموثق لكل موضوع.',
        'btn_start_browsing' => 'ابدأ تصفح الدليل الآن',
        'card_contributor_title' => 'انضم كعضو مساهم',
        'card_contributor_desc' => 'هل أنت شغوف بالأبحاث ومعجزات القرآن؟ سجل حساب مساهم لإضافة وتحديث البيانات وربطها بالآيات المناسبة وإثراء الموسوعة العلمية.',
        'bullet_contributor_1' => 'إضافة مواضيع إعجاز جديدة مشفوعة بالقرائن.',
        'bullet_contributor_2' => 'تفعيل الحساب مباشرة بعد مراجعته من المشرف العام.',
        'bullet_contributor_3' => 'الحفاظ على نزاهة الأبحاث تحت أعلى معايير الأمان.',
        'btn_register_account' => 'سجل حساب مساهم جديد',
        'footer_copyright' => 'تحليلات القرآن. نشر إعجاز ومحاسن القرآن الكريم للعالم أجمع.',
        'footer_tag' => 'تطوير لأغراض دعوية وتعليمية.',
        'superadmin_console' => 'لوحة تحكم المشرف العام',
        'lang_en' => 'English',
        'lang_ar' => 'العربية',
        'lang_id' => 'Bahasa Indonesia',
        
        // login.php & register.php intro
        'login_intro_title' => 'مشروع التحليلات القرآنية والإعجاز العلمي',
        'login_intro_desc' => 'مرحباً بك في المنصة الرقمية التفاعلية المخصصة لعرض ودراسة آيات الإعجاز العلمي في القرآن الكريم. تتيح لك المنصة البحث الفوري في الآيات، واستكشاف الدلائل والمعجزات الكونية والطبية، وتتبع الإحصائيات عبر لوحة التحكم.',
        'feat_quran_title' => 'تصفح القرآن الكريم والبحث',
        'feat_quran_desc' => 'واجهة بحث ذكية وفورية للوصول للآيات وتتبع تكرار الكلمات والمواضيع القرآنية.',
        'feat_miracles_title' => 'موسوعة الإعجاز العلمي',
        'feat_miracles_desc' => 'استكشاف المعجزات المقسمة علمياً (الفلك، الجيولوجيا، الطب، البحار) بأسلوب شيق ومدعم بالحقائق.',
        'feat_dash_title' => 'تحليلات وإدارة ذكية للمحتوى',
        'feat_dash_desc' => 'لوحة تحكم تفاعلية للمشرفين والطلاب لمتابعة الإحصائيات، وإدارة المستخدمين والمعجزات العلمية.',
        
        // login.php
        'login_title' => 'تسجيل الدخول | نظام إدارة الجلسات',
        'auth_portal' => 'نظام التحقق من الهوية',
        'auth_subtitle' => 'بوابة إدارة الجلسات الآمنة والتحليل القرآني',
        'username' => 'اسم المستخدم',
        'password' => 'كلمة المرور',
        'enter_username' => 'أدخل اسم المستخدم',
        'enter_password' => 'أدخل كلمة المرور',
        'no_account' => 'ليس لديك حساب؟',
        'register_here' => 'سجل حساباً جديداً من هنا',
        'demo_accounts' => 'حسابات تجريبية (مشفرة / نص صريح):',
        'demo_admin' => 'اسم المستخدم: admin | كلمة المرور: admin123',
        'demo_user' => 'اسم المستخدم: demo | كلمة المرور: demo123',
        'copyright' => 'جميع الحقوق محفوظة',
        'logout_success' => 'لقد قمت بتسجيل الخروج بنجاح.',
        'pending_approval' => 'حساب المساهم الخاص بك قيد المراجعة والتحقق من قبل المشرف العام. يرجى المحاولة لاحقاً!',
        'invalid_credentials' => 'اسم المستخدم أو كلمة المرور غير صحيحة.',
        'role_superadmin' => 'مشرف عام',
        'role_contributor' => 'مساهم',
        
        // register.php
        'register_title' => 'إنشاء حساب جديد | تحليلات القرآن',
        'create_account' => 'إنشاء حساب جديد',
        'join_portal' => 'انضم إلى بوابة التحليلات القرآنية والإعجاز العلمي',
        'confirm_password' => 'تأكيد كلمة المرور',
        'choose_username' => 'اختر اسم المستخدم',
        'at_least_6' => 'يجب أن تكون كلمة المرور 6 خانات على الأقل',
        'repeat_password' => 'أعد كتابة كلمة المرور',
        'register_button' => 'تسجيل الحساب',
        'already_have' => 'لديك حساب بالفعل؟',
        'sign_in_here' => 'سجل الدخول من هنا',
        'all_fields_required' => 'الرجاء تعبئة جميع الحقول المطلوبة.',
        'passwords_dont_match' => 'كلمات المرور غير متطابقة.',
        'password_too_short' => 'يجب أن تكون كلمة المرور مكونة من 6 خانات على الأقل.',
        'username_taken' => 'اسم المستخدم محجوز بالفعل، يرجى اختيار اسم آخر.',
        'reg_error' => 'حدث خطأ أثناء عملية التسجيل، يرجى المحاولة لاحقاً.',
        'reg_success' => 'تم إنشاء الحساب بنجاح! حسابك قيد المراجعة والموافقة من قبل المدير العام قبل تفعيل دخولك. جاري تحويلك...',
        
        // dashboard.php
        'dash_title' => 'لوحة التحكم | تحليلات القرآن',
        'dash_heading' => 'لوحة تحكم التحليلات وبيانات القرآن',
        'dash_subheading' => 'مرحباً بعودتك! راقب إحصائيات قاعدة البيانات واستكشف معجزات القرآن الكريم العلمية المتكاملة.',
        'scientific_pointers' => 'مواضيع الإعجاز',
        'topics' => 'مواضيع',
        'imported_verses' => 'الآيات المستوردة',
        'verses' => 'آيات',
        'session_privilege' => 'صلاحية الجلسة',
        'superadmin_full' => 'مشرف عام (كامل الصلاحيات)',
        'contributor_add_edit' => 'مساهم (إضافة وتعديل)',
        'available_modules' => 'الأقسام المتاحة',
        'sql_quran_browser' => 'تصفح القرآن الكريم من قاعدة البيانات',
        'quran_browser_desc' => 'تصفح آيات القرآن الكريم مباشرة من قاعدة البيانات. قم بالبحث السريع وعرض البيانات فوراً.',
        'browse_verses' => 'تصفح الآيات',
        'miracles_dir_desc' => 'استكشف الإشارات العلمية في القرآن الكريم، واربط الكلمات الإلهية بالاكتشافات الحديثة في الجيولوجيا والفلك والبحار.',
        'explore_dir' => 'استكشف الدليل',
        'manage_miracles_desc' => 'ساهم بإضافة مواضيع بحثية جديدة، وتعديل الملخصات، أو إثراء قاعدة بيانات عجائب القرآن العلمية.',
        'superadmin_control_desc' => 'راجع وتحقق وفعل حسابات المساهمين الجدد أو أدر حسابات المشرفين للحفاظ على أمان المنصة.',
        'about_project' => 'عن المشروع',
        'about_desc' => 'منصة ويب تعليمية حديثة تربط الدراسات القرآنية بالحقائق العلمية. تم تطويرها بلغة PHP وقاعدة بيانات MySQL تحت بيئة XAMPP للأداء العالي والأمان.',
        'platform_highlights' => 'أبرز مميزات المنصة',
        'protected_sessions' => 'بوابات الجلسات المحمية',
        'prepared_statements' => 'الاستعلامات المهيأة الآمنة',
        'sanitized_inputs' => 'تنقية وفلترة المدخلات',
        
        // quran.php
        'quran_title' => 'القرآن الكريم | تحليلات القرآن',
        'quran_heading' => 'تصفح والبحث في القرآن الكريم (قاعدة البيانات)',
        'quran_subheading' => 'ابحث في آيات القرآن الكريم، أو قم بجلب المصحف كاملاً بضغطة زر واحدة.',
        'download_quran_btn' => 'تحميل المصحف الشريف كاملاً عبر الواجهة البرمجية (بضغطة زر)',
        'select_surah' => 'اختر السورة',
        'no_data_download' => 'لا توجد بيانات (يرجى الضغط على زر التحميل في الأعلى)',
        'search_keywords' => 'البحث بالكلمات المفتاحية (بالعربية أو اسم السورة بالإنجليزية)',
        'search_placeholder' => 'اكتب كلمة البحث... (مثال: الحديد أو Al-Hadid)',
        'search_button' => 'بحث',
        'no_verses_found' => 'لم يتم العثور على آيات',
        'no_verses_desc' => 'تأكد من كتابة كلمة بحث صحيحة أو الضغط على زر تحميل المصحف الشريف في الأعلى لتلقيم قاعدة البيانات.',
        'surah_label' => 'سورة',
        'verse_label' => 'آية',
        'import_conn_error' => 'تعذر الاتصال بالواجهة البرمجية الخارجية للقرآن. يرجى التحقق من اتصال الإنترنت الخاص بك أو المحاولة لاحقاً.',
        'import_success' => 'تم بنجاح! تم تحميل جميع الـ %d آية مباشرة في قاعدة بيانات SQL المحلية.',
        'import_parse_error' => 'فشل في تحليل البيانات المستلمة من الواجهة البرمجية الخارجية.',
        
        // miracles.php
        'miracles_title' => 'الإعجاز العلمي | تحليلات القرآن',
        'miracles_heading' => 'الإعجاز العلمي في القرآن الكريم',
        'miracles_subheading' => 'استكشف الظواهر الجيولوجية والكونية والأرضية التي فصلها القرآن الكريم منذ 14 قرناً.',
        'search_miracles_placeholder' => 'ابحث في معجزات القرآن... (مثال: الحديد، البحار)',
        'quran_meaning_context' => 'المعنى والسياق القرآني',
        'modern_scientific_verification' => 'الإثبات والتحقق العلمي الحديث',
        'no_miracles_found' => 'لم يتم العثور على مواضيع إعجاز',
        'no_miracles_desc' => 'حاول البحث باستخدام كلمات مفتاحية أخرى.',
        'download_quran_prompt' => '(يرجى الضغط على زر تحميل المصحف الشريف في صفحة القرآن الكريم لعرض نص الآية هنا)',
        
        // manage_miracles.php
        'edit_miracle' => 'تعديل موضوع الإعجاز العلمي',
        'add_miracle' => 'إضافة موضوع إعجاز علمي جديد',
        'fill_fields_link' => 'قم بتعبئة الحقول أدناه لربط الموضوع بآية قرآنية محددة.',
        'miracle_title_label' => 'عنوان موضوع الإعجاز',
        'title_placeholder' => 'مثال: الحديد نزل من الفضاء الخارجي',
        'surah_number_label' => 'رقم السورة',
        'ayah_number_label' => 'رقم الآية',
        'meaning_context_desc' => 'المعنى والسياق القرآني (شرح وتفسير)',
        'context_placeholder' => 'اشرح السياق والعمق الإلهي للآية...',
        'scientific_proof_label' => 'الإثبات العلمي الحديث',
        'proof_placeholder' => 'اكتب تفاصيل الاكتشافات الفيزيائية أو الجيولوجية أو الفلكية...',
        'update_entry' => 'تحديث البيانات',
        'add_to_encyclopedia' => 'إضافة إلى الموسوعة',
        'cancel_edit' => 'إلغاء التعديل',
        'manage_existing_entries' => 'إدارة المواضيع الحالية',
        'browse_modify_delete' => 'تصفح مواضيع الإعجاز العلمي، قم بتعديل تفاصيلها، أو حذفها.',
        'miracle_title_th' => 'عنوان الموضوع',
        'reference_th' => 'المرجع',
        'actions_th' => 'العمليات',
        'edit_action' => 'تعديل',
        'delete_action' => 'حذف',
        'confirm_delete_miracle' => 'هل أنت متأكد من رغبتك في حذف هذا الموضوع نهائياً؟',
        'no_records_found' => 'لا توجد سجلات في قاعدة البيانات حالياً. أضف واحداً باستخدام النموذج على اليمين.',
        'add_success' => 'تم إضافة معجزة علمية جديدة بنجاح!',
        'add_error' => 'حدث خطأ أثناء إدراج البيانات.',
        'update_success' => 'تم تحديث موضوع الإعجاز العلمي بنجاح!',
        'update_error' => 'حدث خطأ أثناء تحديث البيانات.',
        'delete_success' => 'تم حذف موضوع الإعجاز العلمي بنجاح.',
        'delete_error' => 'حدث خطأ أثناء حذف البيانات.',
        
        // manage_users.php
        'manage_users_title' => 'إدارة المستخدمين | تحليلات القرآن',
        'add_new_user' => 'إضافة مستخدم جديد',
        'register_user_privileges' => 'تسجيل مستخدم جديد في النظام مع منحه صلاحيات مساهم أو صلاحيات إدارية كاملة.',
        'user_role_label' => 'صلاحية المستخدم',
        'role_contributor_option' => 'مساهم (إضافة وتعديل معجزات)',
        'role_superadmin_option' => 'مشرف عام (صلاحية كاملة)',
        'register_user_btn' => 'تسجيل حساب المستخدم',
        'system_user_directory' => 'دليل مستخدمي النظام',
        'browse_verify_users' => 'تصفح المستخدمين المسجلين، التحقق من المساهمين، إدارة الصلاحيات وحذف الحسابات.',
        'username_th' => 'اسم المستخدم',
        'access_level_th' => 'مستوى الصلاحية',
        'status_th' => 'الحالة',
        'reg_date_th' => 'تاريخ التسجيل',
        'current_session' => 'الجلسة الحالية',
        'approve_action' => 'تفعيل',
        'suspend_action' => 'تعليق',
        'confirm_delete_user' => 'هل أنت متأكد من رغبتك في حذف هذا المستخدم نهائياً؟',
        'no_users_found' => 'لا توجد سجلات مستخدمين في قاعدة البيانات.',
        'username_taken_error' => 'اسم المستخدم محجوز بالفعل. يرجى اختيار اسم مستخدم آخر.',
        'user_reg_success' => 'تم تسجيل المستخدم بنجاح!',
        'user_reg_error' => 'فشل إدراج المستخدم في قاعدة البيانات.',
        'self_delete_error' => 'تنبيه أمني: لا يمكنك حذف حسابك الشخصي الذي تستخدمه حالياً!',
        'user_delete_success' => 'تم حذف المستخدم بنجاح.',
        'user_delete_error' => 'حدث خطأ أثناء حذف المستخدم.',
        'contributor_approved' => 'تم تفعيل حساب المساهم بنجاح!',
        'contributor_approve_error' => 'فشل تفعيل حساب المساهم.',
        'self_suspend_error' => 'تنبيه أمني: لا يمكنك تعليق حسابك الإداري الذي تستخدمه حالياً!',
        'contributor_suspended' => 'تم تعليق الحساب بنجاح.',
        'contributor_suspend_error' => 'فشل تعليق الحساب.',
        'status_active' => 'نشط',
        'status_pending' => 'قيد المراجعة',
        'status_suspended' => 'معلق',
    ],
    'id' => [
        'dir' => 'ltr',
        'brand' => 'Analisis Quran',
        'home' => 'Home',
        'dashboard' => 'Dasbor',
        'quran' => 'Al-Quran',
        'miracles' => 'Mukjizat Ilmiah',
        'manage_miracles' => 'Kelola Mukjizat',
        'manage_users' => 'Kelola Pengguna',
        'welcome' => 'Selamat Datang',
        'guest' => 'Tamu',
        'sign_in' => 'Masuk',
        'become_contributor' => 'Menjadi Kontributor',
        'logout' => 'Keluar',
        'dakwah_badge' => 'Platform Dakwah untuk Wawasan Al-Quran',
        'hero_title' => 'Jelajahi Keajaiban Ilmiah dari',
        'hero_span' => 'Al-Quran Al-Karim',
        'hero_desc' => 'Selamat datang di Quran Analytics. Sebuah sumber edukasi modern yang didedikasikan untuk membagikan mukjizat ilmiah Al-Quran dalam bidang astronomi, oseanografi, geologi, dan biologi manusia. Diturunkan 14 abad yang lalu, teks ilahi ini berdiri dalam harmoni yang sempurna dengan penemuan empiris modern.',
        'btn_explore' => 'Jelajahi Mukjizat Ilmiah',
        'btn_browse_quran' => 'Telusuri Al-Quran',
        'stat_verses' => 'Ayat Al-Quran di DB',
        'stat_miracles' => 'Mukjizat Didokumentasikan',
        'stat_contributors' => 'Kontributor Aktif',
        'card_seeker_title' => 'Untuk Pencari & Pelajar',
        'card_seeker_desc' => 'Platform ini dipertahankan 100% gratis dan terbuka, dengan sama sekali tidak memerlukan login untuk penjelajahan umum. Dirancang sangat mudah diakses dan intuitif untuk teman-teman, siswa, dan pencari kebenaran.',
        'bullet_seeker_1' => 'Baca ayat Al-Quran dalam rasm Utsmani asli.',
        'bullet_seeker_2' => 'Lakukan pencarian kata kunci instan di semua ayat.',
        'bullet_seeker_3' => 'Baca peta konsensus ilmiah yang disusun untuk setiap topik.',
        'btn_start_browsing' => 'Mulai Jelajahi Direktori',
        'card_contributor_title' => 'Bergabung sebagai Kontributor',
        'card_contributor_desc' => 'Apakah Anda bersemangat tentang penelitian dan mukjizat ilmiah Al-Quran? Daftar sebagai kontributor untuk menambah dan memperbarui entri, menghubungkannya ke ayat-ayat tertentu, dan membantu memperkaya basis data kami.',
        'bullet_contributor_1' => 'Kirim topik baru dengan referensi & data ilmiah.',
        'bullet_contributor_2' => 'Validasi tunda-ke-aktif yang aman oleh superadmin.',
        'bullet_contributor_3' => 'Jaga integritas penelitian di bawah keamanan mutlak.',
        'btn_register_account' => 'Daftar Akun Kontributor',
        'footer_copyright' => 'Quran Analytics. Membagikan mukjizat Al-Quran ke seluruh dunia.',
        'footer_tag' => 'Dikembangkan untuk tujuan Dakwah & Pendidikan.',
        'superadmin_console' => 'Konsol Superadmin',
        'lang_en' => 'English',
        'lang_ar' => 'العربية',
        'lang_id' => 'Bahasa Indonesia',
        
        // login.php & register.php intro
        'login_intro_title' => 'Proyek Analisis Quran & Mukjizat Ilmiah',
        'login_intro_desc' => 'Selamat datang di platform digital interaktif yang didedikasikan untuk menampilkan dan mempelajari mukjizat ilmiah dalam Al-Quran. Cari ayat, jelajahi bukti kosmis/medis, dan pantau statistik melalui dasbor.',
        'feat_quran_title' => 'Telusuri Al-Quran & Cari',
        'feat_quran_desc' => 'Antarmuka pencarian pintar dan instan untuk mengakses ayat, melacak kemunculan kata, dan topik Al-Quran.',
        'feat_miracles_title' => 'Ensiklopedia Mukjizat Ilmiah',
        'feat_miracles_desc' => 'Jelajahi mukjizat yang diklasifikasikan secara ilmiah (astronomi, geologi, kedokteran, laut) dengan cara yang menarik dan didukung fakta.',
        'feat_dash_title' => 'Analisis & Manajemen Konten Pintar',
        'feat_dash_desc' => 'Dasbor interaktif untuk admin dan siswa untuk memantau statistik, mengelola pengguna, dan mukjizat ilmiah.',
        
        // login.php
        'login_title' => 'Masuk | Sistem Manajemen Sesi',
        'auth_portal' => 'Portal Verifikasi Identitas',
        'auth_subtitle' => 'Gerbang Sesi Aman & Analisis Al-Quran',
        'username' => 'Nama Pengguna',
        'password' => 'Kata Sandi',
        'enter_username' => 'Masukkan nama pengguna',
        'enter_password' => 'Masukkan kata sandi',
        'no_account' => 'Belum punya akun?',
        'register_here' => 'Daftar akun baru di sini',
        'demo_accounts' => 'Akun Demo (Hashed/Plain):',
        'demo_admin' => 'Nama Pengguna: admin | Kata Sandi: admin123',
        'demo_user' => 'Nama Pengguna: demo | Kata Sandi: demo123',
        'copyright' => 'Hak cipta dilindungi undang-undang',
        'logout_success' => 'Anda telah berhasil keluar.',
        'pending_approval' => 'Akun kontributor Anda sedang menunggu persetujuan oleh Superadmin. Silakan periksa kembali nanti!',
        'invalid_credentials' => 'Nama pengguna atau kata sandi salah.',
        'role_superadmin' => 'Superadmin',
        'role_contributor' => 'Kontributor',
        
        // register.php
        'register_title' => 'Daftar | Analisis Quran',
        'create_account' => 'Buat Akun',
        'join_portal' => 'Bergabung dengan Portal Analisis & Mukjizat Quran',
        'confirm_password' => 'Konfirmasi Kata Sandi',
        'choose_username' => 'Pilih nama pengguna',
        'at_least_6' => 'Minimal 6 karakter',
        'repeat_password' => 'Ulangi kata sandi Anda',
        'register_button' => 'Daftar Akun',
        'already_have' => 'Sudah punya akun?',
        'sign_in_here' => 'Masuk di Sini',
        'all_fields_required' => 'Silakan isi semua bidang yang diperlukan.',
        'passwords_dont_match' => 'Kata sandi tidak cocok.',
        'password_too_short' => 'Kata sandi harus minimal 6 karakter.',
        'username_taken' => 'Nama pengguna sudah digunakan, silakan pilih yang lain.',
        'reg_error' => 'Terjadi kesalahan saat pendaftaran, silakan coba lagi nanti.',
        'reg_success' => 'Akun berhasil dibuat! Menunggu verifikasi Superadmin sebelum Anda dapat masuk. Mengalihkan...',
        
        // dashboard.php
        'dash_title' => 'Dasbor | Quran Analytics',
        'dash_heading' => 'Analisis Dasbor & Data Quran',
        'dash_subheading' => 'Selamat datang kembali! Pantau statistik basis data dan jelajahi mukjizat ilmiah terintegrasi dalam Al-Quran.',
        'scientific_pointers' => 'Petunjuk Ilmiah',
        'topics' => 'Topik',
        'imported_verses' => 'Ayat Diimpor',
        'verses' => 'Ayat',
        'session_privilege' => 'Hak Sesi',
        'superadmin_full' => 'Superadmin (Akses Penuh)',
        'contributor_add_edit' => 'Kontributor (Tambah/Edit)',
        'available_modules' => 'Modul yang Tersedia',
        'sql_quran_browser' => 'Penjelajah Al-Quran Basis Data SQL',
        'quran_browser_desc' => 'Telusuri ayat-ayat Al-Quran langsung dari basis data SQL Anda. Lakukan pencarian kata kunci cepat dan lihat data terjemahan secara instan.',
        'browse_verses' => 'Telusuri Ayat',
        'miracles_dir_desc' => 'Jelajahi pernyataan ilmiah dalam Al-Quran, menghubungkan firman Tuhan secara langsung dengan penemuan modern dalam geologi, astronomi, dan oseanografi.',
        'explore_dir' => 'Jelajahi Direktori',
        'manage_miracles_desc' => 'Kontribusikan topik penelitian baru, edit ringkasan, atau perkaya basis data keajaiban ilmiah Al-Quran.',
        'superadmin_control_desc' => 'Tinjau, verifikasi, dan aktifkan kontributor yang tertunda atau kelola akun admin untuk menjaga keamanan platform.',
        'about_project' => 'Tentang Projek',
        'about_desc' => 'Platform web edukasi modern yang menghubungkan studi Al-Quran dengan realitas ilmiah. Dikembangkan dalam PHP dan terintegrasi dengan MySQL/MariaDB menggunakan XAMPP untuk performa dan keamanan tinggi.',
        'platform_highlights' => 'Sorotan Platform',
        'protected_sessions' => 'Gerbang Sesi Terlindungi',
        'prepared_statements' => 'Pernyataan SQL yang Disiapkan',
        'sanitized_inputs' => 'Input Formulir yang Disanitasi',
        
        // quran.php
        'quran_title' => 'Al-Quran | Quran Analytics',
        'quran_heading' => 'Telusuri & Cari Al-Quran (Basis Data SQL)',
        'quran_subheading' => 'Cari melalui ayat-ayat Al-Quran, atau ambil seluruh kitab suci melalui penginstal satu klik.',
        'download_quran_btn' => 'Unduh Al-Quran Lengkap via API (1-Klik)',
        'select_surah' => 'Pilih Surah',
        'no_data_download' => 'Tidak ada data (Silakan klik tombol Unduh di atas)',
        'search_keywords' => 'Cari Kata Kunci (Bahasa Arab Utsmani atau nama Surah Inggris)',
        'search_placeholder' => 'Ketik kata kunci pencarian... (misal: الحديد, Al-Hadid)',
        'search_button' => 'Cari',
        'no_verses_found' => 'Tidak ada ayat yang ditemukan',
        'no_verses_desc' => 'Pastikan Anda telah mengetik kata kunci yang valid atau mengklik "Unduh Al-Quran Lengkap" di atas untuk mengisi basis data.',
        'surah_label' => 'Surah',
        'verse_label' => 'Ayat',
        'import_conn_error' => 'Tidak dapat terhubung ke API Quran eksternal. Silakan periksa koneksi internet Anda atau coba lagi nanti.',
        'import_success' => 'Berhasil! Memuat semua %d ayat langsung ke basis data SQL lokal Anda.',
        'import_parse_error' => 'Gagal mengurai data yang diterima dari API eksternal.',
        
        // miracles.php
        'miracles_title' => 'Mukjizat Ilmiah | Quran Analytics',
        'miracles_heading' => 'Mukjizat Ilmiah dalam Al-Quran',
        'miracles_subheading' => 'Jelajahi fenomena geologis, kosmis, dan terestrial yang dirinci dalam Al-Quran 14 abad yang lalu.',
        'search_miracles_placeholder' => 'Cari mukjizat ilmiah... (misal: Besi, Laut)',
        'quran_meaning_context' => 'Makna & Konteks Al-Quran',
        'modern_scientific_verification' => 'Verifikasi Ilmiah Modern',
        'no_miracles_found' => 'Tidak ada mukjizat yang ditemukan',
        'no_miracles_desc' => 'Coba cari menggunakan kata kunci yang berbeda.',
        'download_quran_prompt' => '(Silakan klik "Unduh Al-Quran Lengkap" di halaman Al-Quran untuk menampilkan ayat di sini)',
        
        // manage_miracles.php
        'edit_miracle' => 'Edit Mukjizat Ilmiah',
        'add_miracle' => 'Tambah Mukjizat Ilmiah',
        'fill_fields_link' => 'Isi bidang di bawah ini untuk menghubungkan entri ke ayat Al-Quran tertentu.',
        'miracle_title_label' => 'Judul Topik Mukjizat',
        'title_placeholder' => 'misal: Besi Diturunkan dari luar angkasa',
        'surah_number_label' => 'Nomor Surah',
        'ayah_number_label' => 'Nomor Ayat',
        'meaning_context_desc' => 'Makna & Konteks Al-Quran (Deskripsi)',
        'context_placeholder' => 'Jelaskan konteks ilahi dan latar belakang...',
        'scientific_proof_label' => 'Bukti Ilmiah Modern',
        'proof_placeholder' => 'Rincikan penemuan astrofisika, geologi, atau oseanografi...',
        'update_entry' => 'Perbarui Entri',
        'add_to_encyclopedia' => 'Tambahkan ke Ensiklopedia',
        'cancel_edit' => 'Batalkan Edit',
        'manage_existing_entries' => 'Kelola Entri yang Ada',
        'browse_modify_delete' => 'Telusuri mukjizat ilmiah, ubah rinciannya, atau hapus.',
        'miracle_title_th' => 'Judul Mukjizat',
        'reference_th' => 'Referensi',
        'actions_th' => 'Tindakan',
        'edit_action' => 'Edit',
        'delete_action' => 'Hapus',
        'confirm_delete_miracle' => 'Apakah Anda yakin ingin menghapus entri mukjizat ilmiah ini secara permanen?',
        'no_records_found' => 'Tidak ada catatan ditemukan dalam basis data. Buat satu menggunakan formulir di sebelah kiri.',
        'add_success' => 'Mukjizat ilmiah berhasil ditambahkan!',
        'add_error' => 'Terjadi kesalahan saat memasukkan data.',
        'update_success' => 'Mukjizat ilmiah berhasil diperbarui!',
        'update_error' => 'Terjadi kesalahan saat memperbarui data.',
        'delete_success' => 'Mukjizat ilmiah berhasil dihapus.',
        'delete_error' => 'Terjadi kesalahan saat menghapus data.',
        
        // manage_users.php
        'manage_users_title' => 'Kelola Pengguna | Quran Analytics',
        'add_new_user' => 'Tambah Pengguna Baru',
        'register_user_privileges' => 'Daftarkan pengguna sistem baru dengan hak kontributor standar atau administratif.',
        'user_role_label' => 'Peran Pengguna',
        'role_contributor_option' => 'Kontributor (Tambah & Edit Mukjizat)',
        'role_superadmin_option' => 'Superadmin (Akses Penuh)',
        'register_user_btn' => 'Daftar Akun Pengguna',
        'system_user_directory' => 'Direktori Pengguna Sistem',
        'browse_verify_users' => 'Telusuri pengguna terdaftar, verifikasi kontributor, kelola peran, dan hapus akun.',
        'username_th' => 'Nama Pengguna',
        'access_level_th' => 'Tingkat Akses',
        'status_th' => 'Status',
        'reg_date_th' => 'Tanggal Registrasi',
        'current_session' => 'Sesi Saat Ini',
        'approve_action' => 'Setujui',
        'suspend_action' => 'Tangguhkan',
        'confirm_delete_user' => 'Apakah Anda yakin ingin menghapus pengguna ini secara permanen?',
        'no_users_found' => 'Tidak ada catatan ditemukan dalam basis data.',
        'username_taken_error' => 'Nama pengguna sudah digunakan. Silakan pilih yang lain.',
        'user_reg_success' => 'Pengguna berhasil terdaftar!',
        'user_reg_error' => 'Gagal memasukkan pengguna ke dalam basis data.',
        'self_delete_error' => 'Peringatan Keamanan: Anda tidak dapat menghapus akun admin Anda sendiri yang sedang masuk!',
        'user_delete_success' => 'Pengguna berhasil dihapus.',
        'user_delete_error' => 'Terjadi kesalahan saat menghapus pengguna.',
        'contributor_approved' => 'Akun kontributor berhasil disetujui dan diaktifkan!',
        'contributor_approve_error' => 'Gagal menyetujui kontributor.',
        'self_suspend_error' => 'Peringatan Keamanan: Anda tidak dapat menangguhkan akun admin Anda sendiri yang sedang masuk!',
        'contributor_suspended' => 'Akun pengguna berhasil ditangguhkan.',
        'contributor_suspend_error' => 'Gagal menangguhkan akun.',
        'status_active' => 'Aktif',
        'status_pending' => 'Tertunda',
        'status_suspended' => 'Ditangguhkan',
    ]
];

// Helper translation function
function __($key) {
    global $translations, $lang;
    return isset($translations[$lang][$key]) ? $translations[$lang][$key] : $key;
}

// Get current directory direction (RTL or LTR)
function get_dir() {
    global $translations, $lang;
    return isset($translations[$lang]['dir']) ? $translations[$lang]['dir'] : 'ltr';
}
